<?php

namespace CodersLabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonsRepository extends EntityRepository {
    
    public function getPersonByPartOfName($partOfName) {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "SELECT person
            FROM CodersLabBundle:Persons person WHERE
            person.surname LIKE '$partOfName%'");

        return $query->getResult();
    }
    
    public function getPersonsForSurname($string) {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "SELECT person
            FROM CodersLabBundle:Persons person WHERE
            person.surname LIKE '%$string%'");

        return $query->getResult();
    }
    
        public function getPersonsForName($string) {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "SELECT person
            FROM CodersLabBundle:Persons person WHERE
            person.name LIKE '%$string%'");

        return $query->getResult();
    }
    
    
}
